package lifecycle
package main

import (
































































































































































}	fmt.Println("  • 适合管理数据库、缓存等需要启动/关闭的资源")	fmt.Println("  • OnStop 钩子按相反顺序执行")	fmt.Println("  • OnStart 钩子按注册顺序执行")	fmt.Println("\n💡 学习要点：")		app.Run()	)		}),			})				},					return nil					}()						shutdowner.Shutdown()						time.Sleep(500 * time.Millisecond)					go func() {					// 执行完毕后关闭应用										service.GetUser("user456")					service.GetUser("user123")					fmt.Println("\n=== 所有组件已启动，开始执行业务逻辑 ===")				OnStart: func(ctx context.Context) error {			lc.Append(fx.Hook{			// 注册一个在所有组件启动后执行的钩子		fx.Invoke(func(service *UserService, lc fx.Lifecycle, shutdowner fx.Shutdowner) {		),			NewUserService,			NewCache,			NewDatabase,			NewSimpleLogger,		fx.Provide(	app := fx.New(	fmt.Println("=== fx 生命周期管理示例 ===\n")func main() {}	s.logger.Log(dbResult)	dbResult := s.db.Query(fmt.Sprintf("SELECT * FROM users WHERE id='%s'", id))	// 再查数据库	s.logger.Log(cacheResult)	cacheResult := s.cache.Get(id)	// 先查缓存	s.logger.Log(fmt.Sprintf("\n--- 获取用户 %s ---", id))func (s *UserService) GetUser(id string) {}	}		logger: logger,		cache:  cache,		db:     db,	return &UserService{	logger.Log("✓ UserService 已创建")func NewUserService(db *Database, cache *Cache, logger Logger) *UserService {}	logger Logger	cache  *Cache	db     *Databasetype UserService struct {// UserService 依赖数据库和缓存}	return fmt.Sprintf("✓ 缓存值: %s_cached_data", key)	c.logger.Log(fmt.Sprintf("🗄️  从缓存获取: %s", key))	}		return "❌ 错误：缓存服务未启动"	if !c.started {func (c *Cache) Get(key string) string {}	return cache	})		},			return nil			logger.Log("✓ 缓存服务已停止")			cache.started = false			time.Sleep(100 * time.Millisecond)			logger.Log("⚡ 正在停止缓存服务...")		OnStop: func(ctx context.Context) error {		},			return nil			logger.Log("✓ 缓存服务启动成功")			cache.started = true			time.Sleep(300 * time.Millisecond)			logger.Log("⚡ 正在启动缓存服务...")		OnStart: func(ctx context.Context) error {	lc.Append(fx.Hook{	cache := &Cache{logger: logger}func NewCache(lc fx.Lifecycle, logger Logger) *Cache {}	logger  Logger	started booltype Cache struct {// Cache 模拟缓存服务}	return "✓ 查询结果: [用户数据...]"	db.logger.Log(fmt.Sprintf("📝 执行查询: %s", sql))	}		return "❌ 错误：数据库未连接"	if !db.connected {func (db *Database) Query(sql string) string {}	return db	})		},			return nil			logger.Log("✓ 数据库连接已关闭")			db.connected = false			time.Sleep(200 * time.Millisecond)			logger.Log("🔌 正在断开数据库连接...")		OnStop: func(ctx context.Context) error {		},			return nil			logger.Log("✓ 数据库连接成功")			db.connected = true			time.Sleep(500 * time.Millisecond)			logger.Log("🔌 正在连接数据库...")		OnStart: func(ctx context.Context) error {	lc.Append(fx.Hook{	db := &Database{logger: logger}func NewDatabase(lc fx.Lifecycle, logger Logger) *Database {}	logger    Logger	connected booltype Database struct {// Database 模拟数据库连接}	fmt.Printf("[LOG] %s\n", message)func (l *SimpleLogger) Log(message string) {}	return &SimpleLogger{}func NewSimpleLogger() Logger {type SimpleLogger struct{}}	Log(message string)type Logger interface {// Logger 接口)	"go.uber.org/fx"	"time"	"fmt"	"context"