package httpserver
package main























































































































}	// 服务器会一直运行，直到收到停止信号（Ctrl+C）	app.Run()	)		}),			// server 已经通过生命周期钩子启动		fx.Invoke(func(server *HTTPServer) {		),			NewHTTPServer,			NewHTTPHandler,			NewConfig,			NewSimpleLogger,		fx.Provide(	app := fx.New(	fmt.Println("=== fx HTTP 服务器示例 ===\n")func main() {}	return httpServer	})		},			return srv.Shutdown(ctx)			logger.Log("⏹️  关闭 HTTP 服务器")		OnStop: func(ctx context.Context) error {		},			return nil			}()				}					logger.Log(fmt.Sprintf("❌ HTTP 服务器错误: %v", err))				if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {			go func() {			logger.Log("   按 Ctrl+C 停止服务器")			logger.Log("   访问 http://localhost:8080")			logger.Log(fmt.Sprintf("🚀 启动 HTTP 服务器，监听端口 %s", config.Port))		OnStart: func(ctx context.Context) error {	lc.Append(fx.Hook{	// 注册生命周期钩子	}		logger: logger,		server: srv,	httpServer := &HTTPServer{	}		Handler: handler,		Addr:    config.Port,	srv := &http.Server{func NewHTTPServer(lc fx.Lifecycle, config *Config, handler *HTTPHandler, logger Logger) *HTTPServer {}	logger Logger	server *http.Servertype HTTPServer struct {// HTTPServer 封装 HTTP 服务器}	}		fmt.Fprintf(w, "404 Not Found\n")		w.WriteHeader(http.StatusNotFound)	default:		fmt.Fprintf(w, "当前时间: %s\n", time.Now().Format(time.RFC3339))	case "/time":		fmt.Fprintf(w, "OK\n")	case "/health":		fmt.Fprintf(w, "欢迎使用 fx HTTP 服务器!\n")	case "/":	switch r.URL.Path {	h.logger.Log(fmt.Sprintf("收到请求: %s %s", r.Method, r.URL.Path))func (h *HTTPHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {}	return &HTTPHandler{logger: logger}func NewHTTPHandler(logger Logger) *HTTPHandler {}	logger Loggertype HTTPHandler struct {// HTTPHandler 处理 HTTP 请求}	}		Port: ":8080",	return &Config{func NewConfig() *Config {}	Port stringtype Config struct {// Config 配置结构}	fmt.Printf("[LOG] %s\n", message)func (l *SimpleLogger) Log(message string) {}	return &SimpleLogger{}func NewSimpleLogger() Logger {type SimpleLogger struct{}// SimpleLogger 实现}	Log(message string)type Logger interface {// Logger 接口)	"go.uber.org/fx"	"time"	"net/http"	"fmt"	"context"import (